<a href="https://colab.research.google.com/github/kunwarsharik/SharikProjects/blob/master/LSTM_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from keras.layers import Dense,LSTM,Bidirectional,TimeDistributed,ConvLSTM2D,Flatten,RepeatVector
from keras.layers.convolutional import MaxPooling1D,Conv1D
from keras.models import Sequential

Using TensorFlow backend.


In [0]:
raw_seq = np.linspace(10,109,100)
x,y=[],[]
s=3
for i in range(len(raw_seq)-s):
    x2=[]
    for j in range(s):
        x2.append(raw_seq[i+j])
    x.append(x2)
    y.append(raw_seq[i+j+1])
x,y=np.array(x),np.array(y)
for i in range(100-s):
    print(x[i],y[i])
#ye univariate(feature), s(timesteps)
#input_shape=n_samples,timesteps,feature(n_variate)
x3=np.reshape(x,(len(x),3, 1))

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 1)))#input_shape=(n_steps, n_features)
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x3, y, epochs=500, verbose=0)
b=np.array([234.0,235.0,236.0])
b=b.reshape(1,3,1)
model.predict(b)

[10. 11. 12.] 13.0
[11. 12. 13.] 14.0
[12. 13. 14.] 15.0
[13. 14. 15.] 16.0
[14. 15. 16.] 17.0
[15. 16. 17.] 18.0
[16. 17. 18.] 19.0
[17. 18. 19.] 20.0
[18. 19. 20.] 21.0
[19. 20. 21.] 22.0
[20. 21. 22.] 23.0
[21. 22. 23.] 24.0
[22. 23. 24.] 25.0
[23. 24. 25.] 26.0
[24. 25. 26.] 27.0
[25. 26. 27.] 28.0
[26. 27. 28.] 29.0
[27. 28. 29.] 30.0
[28. 29. 30.] 31.0
[29. 30. 31.] 32.0
[30. 31. 32.] 33.0
[31. 32. 33.] 34.0
[32. 33. 34.] 35.0
[33. 34. 35.] 36.0
[34. 35. 36.] 37.0
[35. 36. 37.] 38.0
[36. 37. 38.] 39.0
[37. 38. 39.] 40.0
[38. 39. 40.] 41.0
[39. 40. 41.] 42.0
[40. 41. 42.] 43.0
[41. 42. 43.] 44.0
[42. 43. 44.] 45.0
[43. 44. 45.] 46.0
[44. 45. 46.] 47.0
[45. 46. 47.] 48.0
[46. 47. 48.] 49.0
[47. 48. 49.] 50.0
[48. 49. 50.] 51.0
[49. 50. 51.] 52.0
[50. 51. 52.] 53.0
[51. 52. 53.] 54.0
[52. 53. 54.] 55.0
[53. 54. 55.] 56.0
[54. 55. 56.] 57.0
[55. 56. 57.] 58.0
[56. 57. 58.] 59.0
[57. 58. 59.] 60.0
[58. 59. 60.] 61.0
[59. 60. 61.] 62.0
[60. 61. 62.] 63.0
[61. 62. 63.] 64.0
[62. 63. 64.

array([[240.0785]], dtype=float32)

lstm input is 3d but output is 2d interpretation. return_sequence=True 3d output

In [0]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True,input_shape=(3, 1)))#input_shape=(n_steps, n_features)
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x3, y, epochs=500, verbose=0)
b=np.array([234.0,235.0,236.0])
b=b.reshape(1,3,1)
model.predict(b)

array([[235.17403]], dtype=float32)

bidirectional lstm learn input fromm both forward and backward. and concatenate the output. use if you think it can benifit. wrap the first layer in bidir. wrapper.

In [0]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 1)))#input_shape=(n_steps, n_features)
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x3, y, epochs=500, verbose=0)
b=np.array([234.0,235.0,236.0])
b=b.reshape(1,3,1)
model.predict(b)

array([[237.73886]], dtype=float32)

in "cnn lstm". cnn u to 2d pr kaam krta h. pr 1-d data like univariate series me bi effectively feature extract kr sakta h. iska output lstm process krta h.
n_samples,n_subseq,timesteps,feature(n_variate)

In [0]:
raw_seq = np.linspace(10,109,100)
x,y=[],[]
s=4
for i in range(len(raw_seq)-s):
    x2=[]
    for j in range(s):
        x2.append(raw_seq[i+j])
    x.append(x2)
    y.append(raw_seq[i+j+1])
x,y=np.array(x),np.array(y)
for i in range(100-s):
    print(x[i],y[i])
x4=x.reshape(len(x),2,2,1)

cnn layer use krte h timedistr. wrapper m. timesteps, feature input m dalte h. hr subseq pr cnn chalta h sepeartly.

In [0]:
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, 2, 1)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x4, y, epochs=500, verbose=0)
b=np.array([234.0,235.0,236.0,237.0])
b=b.reshape(1,2,2,1)
model.predict(b)

array([[240.411]], dtype=float32)

ConvLSTM me conv jo read krta h input LSTM layer me diya h. phle cnn part baad me lstm part. u to 2d spatio temporal data k liye h. pr timeseries m bi use kr sakte h. yha 2d ki form mm dena h. Upar ki tarah yaha 1d conv alag se ni laga sakte.

In [0]:
#input (sample,timesteps,row,col,feature)
raw_seq = np.linspace(10,109,100)
x,y=[],[]
s=4
for i in range(len(raw_seq)-s):
    x2=[]
    for j in range(s):
        x2.append(raw_seq[i+j])
    x.append(x2)
    y.append(raw_seq[i+j+1])
x,y=np.array(x),np.array(y)
x4=x.reshape(len(x),2,1,2,1)#1row,2col,in 2timstep, 1 feature

In [0]:
model = Sequential()
model.add(ConvLSTM2D(filters=64,kernel_size=(1,2),activation='relu',input_shape=(2,1,2,1)))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x4, y, epochs=500, verbose=0)
b=np.array([234.0,235.0,236.0,237.0])
b=b.reshape(1,2,1,2,1)
model.predict(b)

array([[234.28487]], dtype=float32)

o1 ki row 1 timestep h. col 1 seq tha.

In [0]:
#multivariate data, when we have more than observation in a timestep.
s1=np.linspace(10,109,100)
s2=np.linspace(110,209,100)
o1=[[i,j,i+j] for i,j in zip(s1,s2)]
no1=np.array(o1)
x,y=[],[]#among 2 types of multivariate series this format is 1st called muliple input series 
s=3
e=2
for i in range(100-s):
    x2=[]
    for j in range(s):
        x3=[]
        for k in range(2):
            x3.append(no1[i+j][k])
        x2.append(x3)
    y.append(no1[i+j][k+1])
    x.append(x2)
x,y=np.array(x),np.array(y)
for i in range(5):
    print(x[i],y[i])


[[ 10. 110.]
 [ 11. 111.]
 [ 12. 112.]] 124.0
[[ 11. 111.]
 [ 12. 112.]
 [ 13. 113.]] 126.0
[[ 12. 112.]
 [ 13. 113.]
 [ 14. 114.]] 128.0
[[ 13. 113.]
 [ 14. 114.]
 [ 15. 115.]] 130.0
[[ 14. 114.]
 [ 15. 115.]
 [ 16. 116.]] 132.0


In [0]:
model = Sequential()
model.add(LSTM(50, activation='relu',return_sequences=True, input_shape=(3, 2)))#input_shape=(n_steps, n_features)
model.add(LSTM(50, activation='relu',return_sequences=True))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=500, verbose=0)
b=np.array([[234.0,334.0],[235.0,335.0],[236.0,336.0]])
b=b.reshape(1,3,2)
model.predict(b)

array([[487.99536]], dtype=float32)

In [0]:
s1=np.linspace(10,109,100)#2nd type of multivariate the parallel series
s2=np.linspace(110,209,100)
o1=[i+j for i,j in zip(s1,s2)]
no1=np.array(o1)
x,y=[],[]
s=3
for i in range(100-s):
    x2,y2=[],[]
    for d in [s1,s2,o1]:
        x3=[]
        for j in range(s):        
            
            x3.append(d[i+j])
        x2.append(x3)
        y2.append(d[i+j+1])
    x.append(x2)
    y.append(y2)
x,y=np.array(x),np.array(y)
for i in range(5):
    print(x[i],y[i])

[[ 10.  11.  12.]
 [110. 111. 112.]
 [120. 122. 124.]] [ 13. 113. 126.]
[[ 11.  12.  13.]
 [111. 112. 113.]
 [122. 124. 126.]] [ 14. 114. 128.]
[[ 12.  13.  14.]
 [112. 113. 114.]
 [124. 126. 128.]] [ 15. 115. 130.]
[[ 13.  14.  15.]
 [113. 114. 115.]
 [126. 128. 130.]] [ 16. 116. 132.]
[[ 14.  15.  16.]
 [114. 115. 116.]
 [128. 130. 132.]] [ 17. 117. 134.]


In [0]:
model = Sequential()
model.add(LSTM(100, activation='relu',return_sequences=True, input_shape=(3, 3)))#input_shape=(n_steps, n_features)
#model.add(LSTM(50, activation='relu',return_sequences=True))
model.add(LSTM(100, activation='relu'))
model.add(Dense(3))
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000, verbose=0)
b=np.array([[234.0,334.0,568.0],[235.0,335.0,570.0],[236.0,336.0,572.0]])
b=np.transpose(b).reshape(1,3,3)
model.predict(b)

array([[223.68715, 392.7526 , 603.4076 ]], dtype=float32)

multistep lstm is used to obtaining the prediction multiple time step forward.

In [0]:
#two type of models 1st vector output model
s1=np.linspace(10,109,100)
x,y=[],[]
s,o=3,2
for i in range(100-s-o):
    x2,y2=[],[]
    for j in range(s):
        x2.append(s1[i+j])
    for j in range(o):
        y2.append(s1[i+j+o+1])
    x.append(x2)
    y.append(y2)
x,y=np.array(x),np.array(y)
for i in range(5):
    print(x[i],y[i])

[10. 11. 12.] [13. 14.]
[11. 12. 13.] [14. 15.]
[12. 13. 14.] [15. 16.]
[13. 14. 15.] [16. 17.]
[14. 15. 16.] [17. 18.]


In [0]:
x=x.reshape(len(x),3,1)

In [0]:
model = Sequential()
model.add(LSTM(100, activation='relu',return_sequences=True, input_shape=(3, 1)))#input_shape=(n_steps, n_features)
model.add(LSTM(100, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000, verbose=0)
b=np.array([200.0,201.0,202.0])
b=b.reshape(1,3,1)
model.predict(b)

array([[205.4869 , 206.55602]], dtype=float32)

encoder decoder model: esp. developed for problem, where i/o is sequence. also helpful in variable output cases. 

2 sub models will be developed. 1 for reading and interoreting input which gives a fixed len output. this is passed to 2nd model. First this input is repeated no_of_step times to get used once with each step. this is passed to 2nd model, each is convetred into output_seq by 2nd model LSTM. 1st model is  encoder 2nd is decoder.

All these repeated seq, after processing from lSTm layer are processed, by using a single layer wrapped in timedistributed layer. 

In [0]:
x.shape

(95, 3, 1)

In [0]:
y=y.reshape(len(y),2,1)

In [0]:
model=Sequential()
model.add(LSTM(100,activation='relu', input_shape=(3,1)))
model.add(RepeatVector(2))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, verbose=0)
b=np.array([200.0,201.0,202.0])
b=b.reshape(1,3,1)
model.predict(b)

array([[[202.72725],
        [204.03429]]], dtype=float32)

multiple input multi-step output. 

In [0]:
s1=np.linspace(10,109,100)#2nd type of multivariate the parallel series
s2=np.linspace(110,209,100)
o1=[i+j for i,j in zip(s1,s2)]
no1=np.array(o1)
x,y=[],[]
s,e=3,3
for i in range(100-s-e):
    x2,y2=[],[]
    for d in [s1,s2]:
        x3=[]
        for j in range(e):
            x3.append(d[i+j])
        x2.append(x3)
    for j in range(2):
        y2.append(o1[i+e+j-1])
    y.append(y2)
    x2=np.transpose(x2).reshape(e,2)
    x.append(x2)
x,y=np.array(x),np.array(y)
for i in range(5):
    print(x[i],y[i])

[[ 10. 110.]
 [ 11. 111.]
 [ 12. 112.]] [124. 126.]
[[ 11. 111.]
 [ 12. 112.]
 [ 13. 113.]] [126. 128.]
[[ 12. 112.]
 [ 13. 113.]
 [ 14. 114.]] [128. 130.]
[[ 13. 113.]
 [ 14. 114.]
 [ 15. 115.]] [130. 132.]
[[ 14. 114.]
 [ 15. 115.]
 [ 16. 116.]] [132. 134.]


In [0]:
model=Sequential()
model.add(LSTM(100,activation='relu',return_sequences=True, input_shape=(3,2)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=200, verbose=0)
b=np.array([[234.0,334.0],[235.0,335.0],[236.0,336.0]])
b=b.reshape(1,3,2)
model.predict(b)

array([[537.49884, 550.0373 ]], dtype=float32)

In [0]:
s1=np.linspace(10,109,100)
s2=np.linspace(110,209,100)
o1=[i+j for i,j in zip(s1,s2)]
no1=np.array(o1)
x,y=[],[]
s,e=3,3
for i in range(100-s-e-2):
    x2=[]
    for j in range(e):
        x3=[]
        for d in [s1,s2,o1]:
            x3.append(d[i+j])
        x2.append(x3)
    
    y2=[]
    for j in range(e,e+2):
        y3=[]
        for d in [s1,s2,o1]:
            y3.append(d[i+j])
        y2.append(y3)
    
    x.append(x2)
    y.append(y2)
x,y=np.array(x),np.array(y)
for i in range(5):
    print(x[i],y[i])

[[ 10. 110. 120.]
 [ 11. 111. 122.]
 [ 12. 112. 124.]] [[ 13. 113. 126.]
 [ 14. 114. 128.]]
[[ 11. 111. 122.]
 [ 12. 112. 124.]
 [ 13. 113. 126.]] [[ 14. 114. 128.]
 [ 15. 115. 130.]]
[[ 12. 112. 124.]
 [ 13. 113. 126.]
 [ 14. 114. 128.]] [[ 15. 115. 130.]
 [ 16. 116. 132.]]
[[ 13. 113. 126.]
 [ 14. 114. 128.]
 [ 15. 115. 130.]] [[ 16. 116. 132.]
 [ 17. 117. 134.]]
[[ 14. 114. 128.]
 [ 15. 115. 130.]
 [ 16. 116. 132.]] [[ 17. 117. 134.]
 [ 18. 118. 136.]]


In [0]:
model=Sequential()
model.add(LSTM(100,activation='relu', input_shape=(3,3)))
model.add(RepeatVector(2))#no_steps_out
model.add(LSTM(100, activation='relu',return_sequences=True))
model.add(Dense(3))#variables in out_step
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=200, verbose=0)
b=np.array([[234.0,334.0,568.0],[235.0,335.0,570.0],[236.0,336.0,572.0]])
b=b.reshape(1,3,3)
model.predict(b)

array([[[189.1986 , 373.82214, 569.0712 ],
        [188.64691, 371.90997, 570.39545]]], dtype=float32)